###
POST http://localhost:8080/product/create 
Content-Type: application/json

{
    "name": "Coffee",
    "description": "Siêu nét",
    "price": "25000",
    "amount": "0",
    "images": ["https://nld.mediacdn.vn/2020/5/12/23723766-0-image-a-181579697765141-15892455662811158088874.jpg", "https://lepathcoffee.com/wp-content/uploads/2022/01/moi-ngay-uong-1-ly-ca-phe-co-tot-khong-768x1152.jpg" ]
}

###
PUT http://localhost:5000/product/update/6332698673a43d173ae2de28
Content-Type: application/json

{
    "name": "Oki cofe"
}

###
GET http://localhost:5000/product/get 


###
POST http://localhost:8080/user/signup 
Content-Type: application/json

{
    "username": "admin",
    "password": "6688"
   
}

###
POST http://localhost:8080/user/login 
Content-Type: application/json

{
    "username": "admin",
    "password": "6688"
 }